export const buildingInfoList = [
  {
    id: 30001,
    name: "石磨",
    level: 1,
    speedBonus: 0, // 速度加成
    productionBonus: 0, // 产量加成
    description: "可以将小麦磨成面粉，产量和速度随等级提升。",
    price: 1200,
    limitQueue: 3,
    icon: "./assets/buildings/mill.png", // 图标路径
  },
  {
    id: 30002,
    name: "烤箱",
    level: 1,
    speedBonus: 0.,
    productionBonus: 0,
    description: "可以制作面包，等级越高效率越高。",
    price: 2400,
    limitQueue: 3,
    icon: "./assets/buildings/bakery.png",
  },
  {
    id: 30003,
    name: "烧烤架",
    level: 1,
    speedBonus: 0,
    productionBonus: 0,
    description: "适合烧烤肉类和蔬菜，产量和速度随等级提升。",
    price: 5000,
    limitQueue: 3,
    icon: "./assets/buildings/grill.png",
  },
  {
    id: 30004,
    name: "锅",
    level: 1,
    speedBonus: 0,
    productionBonus: 0,
    description: "可以用来熬汤或炖菜，等级越高效率越高。",
    price: 3400,
    limitQueue: 3,
    icon: "./assets/buildings/pot.png",
  },
  {
    id: 30005,
    name: "熔炉",
    level: 1,
    speedBonus: 0,
    productionBonus: 0,
    description: "可以用来冶炼金属，等级越高效率越高。",
    price: 3400,
    limitQueue: 4,
    icon: "./assets/buildings/smelter.png",
  },
  {
    id: 30006,
    name: "魔偶",
    level: 1,
    speedBonus: 0,
    productionBonus: 0,
    description: "使用魔晶驱动的机器人，可以采集和攻击。",
    price: 3400,
    limitQueue: 2,
    icon: "./assets/buildings/robot.png",
  },
    {
    id: 30007,
    name: "祭坛",
    level: 1,
    speedBonus: 0,
    productionBonus: 0,
    description: "神秘建筑，献上一些物品，可以获得魔法物品",
    price: 3400,
    limitQueue: 2,
    icon: "./assets/buildings/altar.png",
  },
      {
    id: 30008,
    name: "劈柴坊",
    level: 1,
    speedBonus: 0,
    productionBonus: 0,
    description: "支付工人一些食物，可以生产木头",
    price: 3400,
    limitQueue: 4,
    icon: "./assets/buildings/PichaiFang.png",
  },
]
