export const cropInfoList = [
  {
    id: 10001,
    name: '小麦',
    type: 'grass',
    growthTime: 3600,
    productId: 20101,          
    minProduct: 5,
    maxProduct: 20,
    level: 1,
    upgradeCost: 50,
    price: 5,
    iconYoung: './assets/crops/wheat1.png',
    iconMature: './assets/crops/wheat2.png',
  },
  {
    id: 10002,
    name: '玉米',
    type: 'grass',
    growthTime: 2400,
    productId: 20102,
    minProduct: 3,
    maxProduct: 6,
    level: 1,
    upgradeCost: 80,
    price: 5,
    iconYoung: './assets/crops/maize1.png',
    iconMature: './assets/crops/maize2.png',
  },
  {
    id: 10003,
    name: '胡萝卜',
    type: 'grass',
    growthTime: 2000,
    productId: 20103,
    minProduct: 4,
    maxProduct: 8,
    level: 1,
    upgradeCost: 60,
    price: 3,
    iconYoung: './assets/crops/carrot1.png',
    iconMature: './assets/crops/carrot2.png',
  },
  {
    id: 10004,
    name: '苹果树',
    type: 'tree',
    growthTime: 14400,
    productId: 20104,
    minProduct: 30,
    maxProduct: 50,
    level: 1,
    upgradeCost: 200,
    price: 60,
    iconYoung: './assets/crops/apple1.png',
    iconMature: './assets/crops/apple2.png',
  },
  {
    id: 10005,
    name: '南瓜',
    type: 'grass',
    growthTime: 1800,
    productId: 20106,
    minProduct: 1,
    maxProduct: 2,
    level: 1,
    upgradeCost: 120,
    price: 5,
    iconYoung: './assets/crops/pumpkin1.png',
    iconMature: './assets/crops/pumpkin2.png',
  },
    {
    id: 10006,
    name: '西红柿',
    type: 'grass',
    growthTime: 1800,
    productId: 20107,
    minProduct: 5,
    maxProduct: 10,
    level: 1,
    upgradeCost: 120,
    price: 5,
    iconYoung: './assets/crops/tomato1.png',
    iconMature: './assets/crops/tomato2.png',
  },  {
    id: 10007,
    name: '卷心菜',
    type: 'grass',
    growthTime: 900,
    productId: 20108,
    minProduct: 1,
    maxProduct: 2,
    level: 1,
    upgradeCost: 120,
    price: 2,
    iconYoung: './assets/crops/cabbage1.png',
    iconMature: './assets/crops/cabbage2.png',
  },  {
    id: 10008,
    name: '草莓',
    type: 'grass',
    growthTime: 900,
    productId: 20105,
    minProduct: 20,
    maxProduct: 30,
    level: 1,
    upgradeCost: 120,
    price: 10,
    iconYoung: './assets/crops/strawberry1.png',
    iconMature: './assets/crops/strawberry2.png',
  }
];
